spring:
  data:
    mongodb:
      database: run-record
eureka:
  client:
    service-url:
      defaultZone: http://localhost:20000/eureka
    prefer-ip-address: true
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id}